[workspace]
resolver = "2"

members = [
    "cli",
    "password-maker",
]

[workspace.package]
edition = "2021"
rust-version = "1.82.0"
authors = ["yutotnh <57719497+yutotnh@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
