name: main flow
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup update
          rustup component add rustfmt
          cargo fmt --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup update
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings

  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup update
          cargo check --workspace --locked

  build_and_test:
    name: build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      # Exclude the test that requires the clipboard on ubuntu-latest.
      # Using xvfb-run allows copying to the clipboard,
      # but reading from the clipboard fails, causing the test to fail.
      - if: matrix.os == 'ubuntu-latest'
        run: xvfb-run cargo test --verbose -- --skip 'tests::output_passwords_to_clipboard'
      # All tests are executed on windows-latest and macos-latest as clipboard is available.
      - if: matrix.os != 'ubuntu-latest'
        run: cargo test --verbose

  msrv:
    name: msrv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack
    - run: |
        rustup update
        cargo hack check --rust-version --workspace --all-targets --ignore-private
